use_frameworks!

target 'BiometryTypeBugWorkaround_Example' do
    pod 'BiometryTypeBugWorkaround', :path => '../'

    target 'BiometryTypeBugWorkaround_Tests' do
        inherit! :search_paths
        pod 'BiometryTypeBugWorkaround', :path => '../'
        pod 'Quick', '~> 1.2.0'
        pod 'Nimble', '~> 7.0.2'
        pod 'FBSnapshotTestCase' , '~> 2.1.4'
        pod 'Nimble-Snapshots' , '~> 6.3.0'
    end
end
